[workspace]
resolver = "3"
members = [
  "oxid",
  "oxid-lsp"
]

[workspace.dependencies]
anyhow = "1.0.98"
tokio = { version = "1.47.1", features = ["full"]}
serde = { version = "1.0.219", features = ["derive"] }
