[package]
name = "oxid"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true

crossterm = "0.29.0"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
ropey = "1.6.1"

oxid-lsp = { path = "../oxid-lsp"}
