[package]
name = "oxid"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
crossterm = "0.29.0"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
oxid-lsp = { path = "../oxid-lsp"}
